artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/Forgetful-coder/Chicken-disease-project/raw/main/Chicken_disease.zip
  local_file : artifacts/data_ingestion/data.zip
  unzip_dir : artifacts/data_ingestion